version: "3.8"
services:
  test123:
    image: test123:latest
    ports:
      - "5100"
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
